version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: sh -c "npm run start"
    ports:
      - "80:3000"
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: sh -c "npm run start"
