version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "1234:1234"
      - "4000:4000"
    environment:
      NODE_ENV: $NODE_ENV
      PM2_PUBLIC_KEY: $PM2_PUBLIC_KEY
      PM2_SECRET_KEY: $PM2_SECRET_KEY
    command: sh -c "npm run start:socket & pm2-runtime src/App.js"
