name: Main 브랜치 배포 자동화

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install npm dependencies in FE
        run: cd frontend && npm install
      - name: Install npm dependencies in BE
        run: cd backend && npm install
      - name: Run Frontend build task
        run: cd frontend && npm run build
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./frontend
          remote: /root/deploy
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.REMOTE_PORT }}
            script: |
              cd /root/deploy
              ls
              cd frontend && npm i && start-storybook -p 80
