name: Main 브랜치 배포 자동화

on:
  push:
    branches:
      - main

jobs:
  Deploy_temp_storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Excute deploy script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && nohup ./deploy.sh &
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
